CREATE DATABASE IF NOT EXISTS copa_renault
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_general_ci;

USE copa_renault;

CREATE TABLE IF NOT EXISTS usuario (
  id INT AUTO_INCREMENT PRIMARY KEY,
  usuario VARCHAR(50) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  es_admin BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS partido (
  id INT AUTO_INCREMENT PRIMARY KEY,
  equipo1 VARCHAR(50) NOT NULL,
  equipo2 VARCHAR(50) NOT NULL,
  deporte VARCHAR(20) NOT NULL DEFAULT 'Futbol',
  rama VARCHAR(20) NOT NULL DEFAULT 'Masculino',
  horario VARCHAR(50) NOT NULL,
  goles_equipo1 INT NULL,
  goles_equipo2 INT NULL
);
